# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit detourr.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
library(knitr)
library(tourr)
library(detourr)
options("knitr.graphics.auto_pdf" = TRUE)
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE,
  out.width = ifelse(is_html_output(), "100%", "\\textwidth")
)


## ---- eval=FALSE, echo=TRUE---------------------------------------------------
#> animate(flea[, 1:6],
#>   grand_tour(d = 2),
#>   display = display_xy()
#> )


## ---- echo=TRUE, eval = knitr::is_html_output(), results="hide"---------------
#> render_gif(
#>   flea[, 1:6],
#>   grand_tour(d = 2),
#>   display_xy(),
#>   "img/flea.gif"
#> )


## ----flea-tourr, fig.cap = "A grand tourr of the flea data rendered as an x-y scatterplot."----
if (knitr::is_latex_output()) {
  render(flea[, 1:6], grand_tour(d = 2),
    display_xy(),
    frames = 1, dev = "png",
    filename = "img/flea.png"
  )
  include_graphics("img/flea.png")
} else {
  include_graphics("img/flea.gif")
}


## ---- eval=FALSE, echo=TRUE---------------------------------------------------
#> tour_function(data, tour_path, display_method)


## ---- echo=TRUE, eval = knitr::is_html_output()-------------------------------
#> animate_tour(flea,
#>   tour_path = grand_tour(2),
#>   display = display_scatter(colour = species)
#> )


## ----pkg-bib, eval = FALSE----------------------------------------------------
#> pkgs <- c(
#>   "htmlwidgets", "plotly",
#>   "crosstalk", "tourr"
#> )
#> write_bib(pkgs, "rpkgs.bib")

